version: 2.1 
jobs:
  compile:
   docker:
      - image: ubuntu-2004:current
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential libncurses5-dev bzip2 git bc wget
           cd redmi2_kernel
           bash build_kernel.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
